name: Build Arch ISO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install archiso
        run: |
          pacman -Sy --noconfirm archiso

      
      - name: Build ISO
        run: |
          cd custom-iso/gnome-calamares
          mkarchiso -v .

      - name: Upload ISO artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: archlinux.iso
          path: out/*.iso
